# Generated by Django 2.1.3 on 2018-11-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='Mascotas',
        ),
    ]
