# Generated by Django 2.1.3 on 2018-11-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0002_auto_20181105_0317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mascotas',
            new_name='Mascota',
        ),
    ]
