# Generated by Django 2.1.3 on 2018-11-25 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0003_auto_20181105_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptantes',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('nombre_full', models.CharField(max_length=100)),
                ('fec_nac', models.DateField()),
                ('fono', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('nom_region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('tipo_vivienda', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='reg_com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescatados.Region'),
        ),
        migrations.AddField(
            model_name='adoptantes',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescatados.Comuna'),
        ),
        migrations.AddField(
            model_name='adoptantes',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescatados.Region'),
        ),
        migrations.AddField(
            model_name='adoptantes',
            name='tipo_vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescatados.Vivienda'),
        ),
    ]
