# Generated by Django 2.1.3 on 2018-11-25 23:33

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('rescatados', '0005_auto_20181125_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adoptantes',
            new_name='Adoptante',
        ),
        migrations.RenameModel(
            old_name='Region',
            new_name='Regione',
        ),
    ]
