# Generated by Django 2.1.3 on 2018-11-25 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0007_auto_20181125_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionComuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescatados.Comuna')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescatados.Regione')),
            ],
        ),
    ]
