# Generated by Django 2.1.3 on 2018-11-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0008_regioncomuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regioncomuna',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='regioncomuna',
            name='region',
        ),
        migrations.DeleteModel(
            name='RegionComuna',
        ),
    ]
