# Generated by Django 2.1.3 on 2018-11-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescatados', '0009_auto_20181125_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='comuna',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='fec_nac',
            field=models.DateField(help_text='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='fono',
            field=models.PositiveIntegerField(help_text='numero de Telefono'),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='region',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='tipo_vivienda',
            field=models.CharField(max_length=80),
        ),
    ]
